/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      screens: {
        '2k': '1921px',
        '3xl': '1921px',
      },
      colors: {
        "on-surface": "#e2e8f0",
        "secondary-fixed-dim": "#93c5fd",
        "tertiary": "#67e8f9",
        "surface": "rgba(11, 18, 35, 0.65)",
        "surface-container-lowest": "rgba(5, 9, 20, 0.45)",
        "background": "#050811",
        "grid-line": "rgba(255, 255, 255, 0.04)",
        "on-secondary-fixed-variant": "#1e3a8a",
        "outline": "rgba(148, 163, 184, 0.25)",
        "zinc-outline": "rgba(255, 255, 255, 0.1)",
        "tertiary-container": "rgba(6, 182, 212, 0.2)",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-background": "#e2e8f0",
        "inverse-surface": "#e2e8f0",
        "surface-variant": "rgba(30, 46, 76, 0.45)",
        "amber-glow": "rgba(56, 189, 248, 0.3)",
        "surface-dim": "rgba(8, 14, 28, 0.55)",
        "surface-container": "rgba(14, 23, 44, 0.6)",
        "inverse-on-surface": "#1e293b",
        "on-primary-fixed-variant": "#075985",
        "on-tertiary": "#083344",
        "surface-container-highest": "rgba(30, 48, 86, 0.55)",
        "on-tertiary-fixed-variant": "#155e75",
        "secondary-container": "rgba(30, 58, 138, 0.3)",
        "on-primary-fixed": "#082f49",
        "surface-container-low": "rgba(10, 16, 32, 0.5)",
        "on-primary": "#030712",
        "primary-fixed-dim": "#38bdf8",
        "outline-variant": "rgba(255, 255, 255, 0.08)",
        "on-secondary-container": "#bfdbfe",
        "inverse-primary": "#0284c7",
        "secondary": "#93c5fd",
        "error-container": "rgba(239, 68, 68, 0.2)",
        "tertiary-fixed": "#cffafe",
        "surface-tint": "#38bdf8",
        "secondary-fixed": "#dbeafe",
        "primary-container": "#0284c7",
        "on-secondary-fixed": "#1e3a8a",
        "surface-container-high": "rgba(20, 32, 60, 0.65)",
        "primary": "#38bdf8",
        "on-secondary": "#1e3a8a",
        "tertiary-fixed-dim": "#67e8f9",
        "primary-fixed": "#e0f2fe",
        "on-tertiary-container": "#083344",
        "on-primary-container": "#0c4a6e",
        "on-surface-variant": "#94a3b8",
        "on-error": "#7f1d1d",
        "on-tertiary-fixed": "#0e7490",
        "zinc-surface": "rgba(15, 23, 42, 0.6)",
        "surface-bright": "rgba(30, 58, 110, 0.5)",
        
        // Shadcn UI base colors mapping
        border: "rgba(255, 255, 255, 0.12)",
        input: "rgba(255, 255, 255, 0.08)",
        ring: "#38bdf8",
        foreground: "#f8fafc",
        card: "rgba(11, 18, 35, 0.6)",
        "card-foreground": "#f8fafc",
        popover: "rgba(8, 14, 28, 0.8)",
        "popover-foreground": "#f8fafc",
        muted: "rgba(30, 46, 76, 0.45)",
        "muted-foreground": "#94a3b8",
        accent: "#38bdf8",
        "accent-foreground": "#030712",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1440px",
        "max-width-2k": "1720px",
        "margin-mobile": "16px",
        "gutter-desktop": "24px",
        "unit": "4px",
        "margin-tablet": "32px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "mono-data": ["Space Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["15px", { "lineHeight": "1.5", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
