/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      screens: {
        '2k': '1921px',
        '3xl': '1921px',
      },
      colors: {
        "on-surface": "#f8fafc",
        "secondary-fixed-dim": "#d0bcff",
        "tertiary": "#ffbbbe",
        "surface": "#111827",
        "surface-container-lowest": "#0b0f19",
        "background": "#090d16",
        "grid-line": "rgba(255, 255, 255, 0.04)",
        "on-secondary-fixed-variant": "#5516be",
        "outline": "rgba(255, 255, 255, 0.15)",
        "zinc-outline": "rgba(255, 255, 255, 0.12)",
        "tertiary-container": "rgba(244, 63, 94, 0.2)",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-background": "#f8fafc",
        "inverse-surface": "#f8fafc",
        "surface-variant": "#1f2937",
        "amber-glow": "rgba(245, 158, 11, 0.3)",
        "surface-dim": "#0d111c",
        "surface-container": "#151d2e",
        "inverse-on-surface": "#1e293b",
        "on-primary-fixed-variant": "#653e00",
        "on-tertiary": "#67001b",
        "surface-container-highest": "#283548",
        "on-tertiary-fixed-variant": "#92002a",
        "secondary-container": "rgba(99, 102, 241, 0.25)",
        "on-primary-fixed": "#2a1700",
        "surface-container-low": "#101624",
        "on-primary": "#472a00",
        "primary-fixed-dim": "#ffb95f",
        "outline-variant": "rgba(255, 255, 255, 0.08)",
        "on-secondary-container": "#c4abff",
        "inverse-primary": "#855300",
        "secondary": "#a5b4fc",
        "error-container": "rgba(239, 68, 68, 0.2)",
        "tertiary-fixed": "#ffdadb",
        "surface-tint": "#ffb95f",
        "secondary-fixed": "#e9ddff",
        "primary-container": "#f59e0b",
        "on-secondary-fixed": "#23005c",
        "surface-container-high": "#1e293b",
        "primary": "#ffc174",
        "on-secondary": "#3c0091",
        "tertiary-fixed-dim": "#ffb2b7",
        "primary-fixed": "#ffddb8",
        "on-tertiary-container": "#8c0028",
        "on-primary-container": "#613b00",
        "on-surface-variant": "#cbd5e1",
        "on-error": "#690005",
        "on-tertiary-fixed": "#40000d",
        "zinc-surface": "#111827",
        "surface-bright": "#2d3748",
        
        // Shadcn UI base colors mapping
        border: "rgba(255, 255, 255, 0.12)",
        input: "rgba(255, 255, 255, 0.08)",
        ring: "#ffc174",
        foreground: "#f8fafc",
        card: "#111827",
        "card-foreground": "#f8fafc",
        popover: "#0f172a",
        "popover-foreground": "#f8fafc",
        muted: "#1f2937",
        "muted-foreground": "#94a3b8",
        accent: "#ffc174",
        "accent-foreground": "#472a00",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1440px",
        "max-width-2k": "1720px",
        "margin-mobile": "16px",
        "gutter-desktop": "24px",
        "unit": "4px",
        "margin-tablet": "32px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "mono-data": ["Space Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["15px", { "lineHeight": "1.5", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
